FROM php:8.4-cli-alpine

RUN docker-php-ext-install pdo_pgsql

WORKDIR /app

COPY public ./public
COPY src ./src

EXPOSE 3000

CMD ["sh", "-c", "php -S 0.0.0.0:${PORT:-3000} -t /app/public /app/public/index.php"]
