FROM php:8.4-cli-alpine

RUN apk add --no-cache postgresql-dev \
    && docker-php-ext-install pdo_pgsql \
    && apk del postgresql-dev

WORKDIR /app

COPY public ./public
COPY src ./src

CMD ["sh", "-c", "php -S 0.0.0.0:${PORT:-80} -t /app/public"]
